import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Layout from './Layout';

const inter = Inter({ subsets: ['cyrillic'] });

export async function getServerSideProps() {
    console.log('yo');
    // Fetch data from external API
    const res = await fetch(
        'https://6230a297f113bfceed575b81.mockapi.io/database/clinics'
    );
    const data = await res.json();
    console.log(data);
    // Pass data to the page via props
    return { props: { data } };
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={inter.className}>
                <Layout />
            </main>
        </>
    );
}
